# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-16 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('book', models.ManyToManyField(to='book.Book')),
            ],
        ),
    ]
